### ISSUE TITLE
Can I access only with hostname? (In local network)

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#1003]
Hello, is there any option to see my **Debian laptop** with Radicale from my **phone Android** but using a hostname and not with an IP?

I am not an expert and the only thing that interests me is to use Radicale on a local network, between my laptop and my phone.

**The scenario** 
My Laptop has Radical installed (it works like the server) but it doesn't always have the same IP because I connect to different Wi-Fi during the week, that's why I'm looking for a way to connect although the IP is always changing.

I tried several configurations between **/etc /radicale /config** and **/etc /hosts** and I can't access from Android with just the hostname, do I need another tool?

**Comment by matthinc** [comment]
Hi,
what you plan could work in some situations, but it's definitively not a stable solution.
The problem is, that you can't communicate "by hostname" in an IP network. It might work in your local network because your router's DNS-server translates the hostname "laptop" to the corresponding IP-address. But you certainly can't rely on this mechanism to work in all networks.

If you want to try this nevertheless, you should add the following lines to your configuration:
```ini
[server]
hosts = 0.0.0.0:5232
```
This ensures that Radicale listens on all possible IP-addresses.

But I'd recommend to rent a cheap server and install Radicale there.
