### ISSUE TITLE
Possible to support vdirsyncer ?

### ISSUE THREAD

**Issue by caywin25** [Kozea/Radicale#1027]
Hello
I have a radicale server and I wish I could use it with khal (https://github.com/pimutils/khal)
Khal use vdirsyncer for event calendar sync. 
But it seems to me that radical isn't compatible with vdirsyncer (http://vdirsyncer.pimutils.org/en/stable/tutorials/radicale.html)
Is it possible to make it compatible with vdirsyncer ?
Thank you very much.

**Comment by jonassmedegaard** [comment]
Quoting caywin25 (2020-04-01 16:42:01)
> I have a radicale server and I wish I could use it with khal (https://github.com/pimutils/khal)
> Khal use vdirsyncer for event calendar sync. 
> But it seems to me that radical isn't compatible with vdirsyncer (http://vdirsyncer.pimutils.org/en/stable/tutorials/radicale.html)
> Is it possible to make it compatible with vdirsyncer ?

The page you are pointing to seems outdated: Try follow the referenced 
bug and see for yourself that it was closed since Radicale 2.0.0rc1

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by caywin25** [comment]
Ah yes my bad sorry.
Works perfectely !!!
I close this issue. 
Regards !
