### ISSUE TITLE
Run radicale on a machine which connects to internet through mobile hotspot?

### ISSUE THREAD

**Issue by internetman420** [Kozea/Radicale#1036]
I guess the title is quite self-explanatory. I would like to run a local CalDav-server, and yours looks good. The thing is that my computer connects to the internet through my smartphone(atleast for the foreseable future), and I am wondering if this will make it very difficult to set it up so that my other devices can sync to it. 

I will have different IP's all the time etc. Any thoughts?

**Comment by jaesivsm** [comment]
For most home servers, yeah, IP change often. But it's worse on mobile network since operators often put some kind of carrier grade NAT in place. Meaning that even the public IP of your access point is one private to the network of your operator. 
Basically you won't be able expose any port to the web nor reach it from the outside. 

Although, if all of your clients are on the same network and you're ok with them syncing only when connected to that network, it doesn't matter much if you're connected to the web at all.

If you really want to reach it from the outside, you might consider tunneling service like ngrok or other. But it's hardly reliable for purpose other than testing.

This is hardly related to Radicale specificities though.

**Comment by internetman420** [comment]
Thank you for your fulfilling answer!
