### ISSUE TITLE
What happened to well-known urls configuration?

### ISSUE THREAD

**Issue by oupala** [Kozea/Radicale#1160]
In [documentation of Radicale 1.x](https://radicale.org/1.1.html), we can find some references to well-known urls:

```
[...]
well-known]

# Path where /.well-known/caldav/ is redirected
#caldav = '/%(user)s/caldav/'

# Path where /.well-known/carddav/ is redirected
#carddav = '/%(user)s/carddav/'
[...]
```

I can't find any reference to well-known urls in [radicale 2.1](https://radicale.org/2.1.html) or [3.0](https://radicale.org/3.0.html) documentation. I can't either find any reference to well-known urls in default configuration files of radicale 2.1 (in `/etc/radicale`).

So, what happened to well-known urls configuration? Are they still supported by radicale?

**Comment by tyll** [comment]
Davx5 seems to work fine without them. If you need them, you can probably add them by using a reverse proxy. I don't have any insights from Radicale development, though.

**Comment by vinerich** [comment]
Just found this poking around.
https://github.com/Kozea/Radicale/commit/fd977891e8016eb5323ab0bfaa58f2f84dfe13ce

Seems like the support has been removed.

**Comment by oupala** [comment]
Thanks a lot @vinerich. I think you spotted the right commit!

This story ends up with a known issue: the feature I was looking for has been removed because of "I can't think of a sane use-case for this."

**Comment by vinerich** [comment]
@oupala No problem!
I forgot where I read it and can't find it rn but: Someone mentioned that you can set up a manual redirect like @tyll said earlier.
I don't know to which URL since I don't know the DAV protocoll well but if i recall it directly it maybe was from `/.well-known` to `/well-known` or to `/`.

If you have an update on this I'd be glad if you could mention me here. I will do the same if I got any news!

I don't like mentioning maintainers directly but maybe @Unrud can shed some light on this issue if he got the time.

### Small recap
[Radicale 1.x](https://radicale.org/1.1.html) supported `/.well-known` urls for (I believe) automated discovery. Some tools like [TbSync](https://github.com/jobisoft/TbSync) send a propfind request to this url to show all available calendars.

This feature is missing in newer versions as it was removed with fd97789. Could we have a small explanation other than the commit description why it was removed?

Thanks in advance and sorry for mentioning directly!
