### ISSUE TITLE
error: unrecognized arguments: --htpasswd-filename

### ISSUE THREAD

**Issue by kousu** [Kozea/Radicale#1176]
The [docs](https://radicale.org/3.0.html#documentation/configuration) say you can pass config-file options on the command line, like this, but it does not work:

```
comms3$ python3 -m radicale --server-hosts 0.0.0.0:5232,[::]:5232 --auth-type htpasswd --htpasswd-filename ~/.config/radicale/users --htpasswd-encryption md5 
usage: radicale [OPTIONS]
radicale: error: unrecognized arguments: --htpasswd-filename /home/kousu/.config/radicale/users --htpasswd-encryption md5
comms3$ python3 -m radicale --version                                                                                                                         
3.0.6
```

**Comment by marcoSchr** [comment]
This seems to be an error in the documentation. The correct argument should be --auth-htpasswd-filename and --auth-htpasswd-encryption.

According to the source code at [radicale/__main__.py#L69](https://github.com/Kozea/Radicale/blob/master/radicale/__main__.py#L69) the allowed arguments are taken from [radicale/config.py#L103](https://github.com/Kozea/Radicale/blob/master/radicale/config.py#L103).
Every argument is prefixed by the group it is in. 
If the option has any alias, you can use them directly.

To fix this, I see 2 options:
1. Change the documentation to reflect the current behaviour
2. Add an alias to the option so that the code reflects the documentation

**Comment by pbiering** [comment]
at least on current documenation the example shows how it works: https://radicale.org/v3.html#configuration
