### ISSUE TITLE
Removal of .well-known complicates client setup

### ISSUE THREAD

**Issue by oliva** [Kozea/Radicale#1200]
Since the removal of .well-known support in commit https://github.com/Kozea/Radicale/commit/fd977891e8016eb5323ab0bfaa58f2f84dfe13ce, client setup requires that the base url is suffixed with the username, which is not trivial on at least the DAVx⁵ client (it's a regression to the 2.x workaround): https://www.davx5.com/tested-with/radicale

**Comment by Unrud** [comment]
Well-Known URIs were removed because they are unnecessary for our use-case. Cllient's will just use `/` if they return 404.
If Radicale is served at a different location by a reverse-proxy (or similar) the Well-Known URIs must be provided by it as well and point to the right location.


> client setup requires that the base url is suffixed with the username

No.

> which is not trivial on at least the DAVx⁵ client

It should work by just providing the domain, username and password.

Maybe you can share more information about your setup to identify the problem.

**Comment by timthelion** [comment]
This deffinitely broke setting up CalDav with the TBSync pluggin on thunderbird. It errors out at:

```
URL:
http://<redacted>/timothy/9442<redacted>c442098/.well-known/carddav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
Access to the requested resource forbidden.
```
