### ISSUE TITLE
Installing Radicale on Centos 7 will not open the Admin login, just shows "Radical works!"

### ISSUE THREAD

**Issue by webscopeny** [Kozea/Radicale#1204]
I installed Radicale on Centos 7 and I can't get to the Web interface. It always displays "Radical works!". Any other folder I try opens a download page and tries to download an .ics file. I'm trying to set it up for address books only. I tried setting "type = internal" but it didn't help. Here's the config file:

[server]
hosts = 0.0.0.0:5232
daemon = True
certificate = /etc/pki/tls/certs/localhost.crt
realm = "Radicale - Password Required"

[web]
type = internal

[auth]
type = htpasswd
htpasswd_filename = /etc/radicale/users
htpasswd_encryption = bcrypt
delay = 1
file = /var/lib/radicale/rights

[storage]

filesystem_folder = /var/lib/radicale/collections

**Comment by Unrud** [comment]
I think you are using a old version. Check `radicale --version`.

**Comment by webscopeny** [comment]
yes, it's version 1.1.2. I used yum to install it. Is it easy to upgrade to 3?

**Comment by pbiering** [comment]
official EPEL7 repository unfortunatly can't support radicale > 1 because major update requires manual interaction. EPEL8 build will not work because of all the Python dependencies, but I've created a scratch build of 2.1.8 in the past (expired since some time). Will try to create an updated one next.

@Unrud : can you assign me that ticket?

**Comment by pbiering** [comment]
Digged deeper and unfortunatly it stays difficult as it already was in the past for EL7. Some by EPEL7 provided python RPMs are too old. In EPEL8 I use a workaround and include required site-packages for Python 3.8 already. As EPEL7 has only Python 3.6 as maximum and e.g. "dateutil" is on version 2.4.2 only while "radicale" requires a newer one I can't use that mechanism. Ugly workaround would be creating additional RPMs overriding current ones from EPEL7...I won't recommend this except you are deep technical.

Here is a scratch build with 2.1.12 and Python 3.6, but it's not installable because of missing dependencies.
https://koji.fedoraproject.org/koji/taskinfo?taskID=82324599

As EL7 without buying Extended Lifecycle Support (ELS) from Red Hat will anyhow run EoS in 2022-06-30 (< 2,5 years from now) I strongly recommend upgrading to EL8 very next...and you can use radicale major version 3 from EPEL out-of-the-box.

**Comment by bgstack15** [comment]
I rebuilt the Fedora Radicale v3 packages for EL7. https://copr.fedorainfracloud.org/coprs/bgstack15/radicale-el7/
