### ISSUE TITLE
Shared Calendar Correct Updated Procedure?

### ISSUE THREAD

**Issue by sysadminpower2019** [Kozea/Radicale#1300]
Hello,

I'd like to create a shared calendar which allows user1 and user2 to read and write from a shared main calendar.
I have looked at several configuration options and it would seem there have been changes from previous versions.
I have seen that there are recommended changes in the rights file, I tested several of them with no results.
I also saw that the previous procedure involved symlinking two calendar files together.

What is the most up to date procedure? Do we still need to symlink the calendar files? It seems like a bit of a hack.

**Comment by pbiering** [comment]
I have such in use since years, based on using softlinks

Directory: /var/lib/radicale/collections/collection-root
```
user1
user2
groups
```

Directory: /var/lib/radicale/collections/collection-root/groups
```
group-1.ics
group-1.vcf
group-2.ics
group-2.vcf
```

Directory: /var/lib/radicale/collections/collection-root/user1
```
user1.ics
user1.vcf
group1.ics -> ../groups/group1.ics
group1.vcf -> ../groups/group2.vcf
```

You can control by softlink, which user should have access to which group calendar.

**Comment by pbiering** [comment]
Calendar sharing is now documented by Wiki https://github.com/Kozea/Radicale/wiki/Sharing-Collections

WebUI is only a javascript UI using CAL/CARDAV protocol and has no direct connection into system at all.

Closing as related discussion already exists https://github.com/Kozea/Radicale/discussions/1499
