### ISSUE TITLE
Radicale + Nginx Proxy Manager = Nope

### ISSUE THREAD

**Issue by F1zzyD** [Kozea/Radicale#1542]
As of now, Radicale is unable to work well with Nginx Proxy Manager. I am trying to put out a calendar link through NPM and send it securely to Cloudflare, however NPM fails to resolve Radicale's address. 

Here's what I want:
- Radicale runs on http://localhost:5232
- NPM forwards "https://test.domain.com" to Radicale's calendar

Here's what I've done

1. Set NPM to forward "https://test.domain.com" to "http://localhost:5232"
2. Set NPM to forward "https://test.domain.com" to for example "http://localhost:5232/user/32095-239048-234908023"
3. Set NPM to use "Custom locations" and put "/user/230945-234590-324589" in the location area
4. Added many variations of code to the Advanced area of NPM
5. Config in Radicale has this:
```
type = htpasswd
htpasswd_filename = /config/users
htpasswd_encryption = md5
SSL = False
hosts = 0.0.0.0:5232
```

What I've made sure of:
- Radicale is up to date
- NPM is up to date
- Information is correct in the config, user, and compose.yml files

So far, nothing seems to work. NPM works with all of my other services but fails to operate with Radicale.

**Comment by pbiering** [comment]
Please setup an "Apache" reverse proxy in parallel with suggested configuration, validate that it's working e.g. by using hints from

- https://github.com/Kozea/Radicale/wiki/Reverse-Proxy-Diagnostics-Troubleshooting
- https://github.com/Kozea/Radicale/wiki/Server-Diagnostics---Troubleshooting (but using reverse proxy port instead of direct connection)

If sucessfully validated, use same commands but pointing to "NPM" host/port and check "NPM" error logs and compare "radicale" debug log with "request_header_on_debug = true" and look for any difference.

**Comment by pbiering** [comment]
No reply anymore, please reopen if still persist and all the troubleshooting did not help, especially check with `ngrep` for any traffic to radicale's listen port
