### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by liZe** [Kozea/Radicale#29]
Radicale should be tested. There's only one test sending a GET request at `/`, and that's a shame.

DAViCal has for example [an excellent testing suite](http://repo.or.cz/w/davical.git/tree/HEAD:/testing/tests/regression-suite).

**Comment by untitaker** [comment]
I don't think using litmus is a realistic option ATM, primarily because it asserts full compliance to the RFCs. @liZe If you want I'll whip up a PR which downloads my CalDAV/CardDAV client and runs its (very basic) testsuite against Radicale. That's how I found all the bugs I've reported in the past.

**Comment by untitaker** [comment]
Bump. I'd be willing to prepare a PR that installs vdirsyncer into Travis, and runs its testsuite against Radicale. The diagnostics and debugging are ugly at the moment, but it does find bugs!

**Comment by untitaker** [comment]
@liZe While I have you on the line, could you respond to my comments above?

**Comment by liZe** [comment]
It's OK for me!

**Comment by liZe** [comment]
Tests seem to be quite good for now, I think that it's enough for 2.0.0.
