### ISSUE TITLE
Calendar Version 8.0: CalDAVAccountRefreshQueueableOperation

### ISSUE THREAD

**Issue by Weuxel** [Kozea/Radicale#354]
Apple Calendar Version 8.0 complains about CalDAVAccountRefreshQueueableOperation did not succeed while refreshing.
There is no radicale log output about this.

**Comment by liZe** [comment]
A lot of work has been done in master, is this issue still relevant?

**Comment by Weuxel** [comment]
I did not encounter this problem in a long time, so i expect it is not relevant any more.
But i forgot about this issue here.

**Comment by liZe** [comment]
Ok, thank you.

**Comment by meitar** [comment]
I have just encountered this issue while using a `file` rights back-end. I'm using Apple Calendar version 8.x (the default on macOS 10.10.x). The issue stemmed from the fact that the rights back-end sample configuration file shown on the Radicale website includes a too-strict collection regex:

```
# Authenticated users can read and write their own collections.
[owner-write]
user = .+
collection = %(login)s/.*
permission = rw
```

This won't work for Apple Calendar.app clients at all, because the slash in the `collection` line causes Radicale to always return a `403 Forbidden` error to the client when they are searching for user calendar collections.

Changing `%(login)s/.*` to `%(login)s/?.*` fixes the issue (notice the addition of the question mark), but a possibly more secure configuration is to add a second authorization block atop this one:

```
# Authenticated users can list (discover) their own collections.
[owner-discover]
user = .+
collection = ^%(login)s$
permission = r

# Authenticated users can read and write their own collections.
[owner-write]
user = .+
collection = %(login)s/.*
permission = rw
```

With *this* rights file configuration, the `owner-discover` block is matched and Radicale allows Apple Calendar clients to enumerate ("auto-discover") the logged-in user's existing calendar collections.

**Comment by Unrud** [comment]
> Changing ``%(login)s/.*`` to ``%(login)s/?.*`` fixes the issue (notice the addition of the question mark), but a possibly more secure configuration is to add a second authorization block atop this one:

You can just use ``%(login)s(/.*)?``. Fixed in 9dfd727b6c1fd9978ca78bdd48ef1470433fef8b.

**Comment by meitar** [comment]
@Unrud Thanks for updating the docs. :)

**Comment by pidydx** [comment]
I have just started run into this with Apple Calendar 10.0.  I am running radicale behind an Apache proxy.  I could have sworn everything was working in my test environment, I deployed, then started getting this CalDAVAccountRefreshQueueableOperation problem, I regenerated my test environment and suddenly the problem was there too.  I'm at a loss for what could have changed or how to troubleshoot this.

I am running owner_only, but I attempted to use from_file as described above and saw no change in behavior.  All of the iOS devices I have are able to access it correctly though so the server itself appears to be working just fine.

**Comment by Weuxel** [comment]
This issue reapears in 2.1.8.

**Comment by ScrumpyJack** [comment]
Confirmed

**Comment by artifex404** [comment]
Confirm this issue when running nginx as reverse proxy. Authentication preformed by Radicale.

**Comment by artifex404** [comment]
Maybe re-open this issue? @liZe
