### ISSUE TITLE
BB10 Carddav Support

### ISSUE THREAD

**Issue by ghost** [Kozea/Radicale#46]
Hi there,

i can use Radicale with BB10 to sync my calendar. Everything works fine, but Carddav does not work, BB10 always says my entered account data is invalid, but i use the same account with my Caldav.

Thanks.

**Comment by singpolyma** [comment]
Do updates work with BB10 for anyone else?  Editing seems to not work... it seems that when I edit a contact BB10 first does a PROPFIND and then does a PUT to /singpolyma/addressbook.vcf/UID.vcf where the UID does not match the UID of the existing contact, and radicale issues `412 Precondition Failed`

**Comment by singpolyma** [comment]
Seems this is likely the result of sending the header:

    'HTTP_IF_MATCH': '"417df693767b12517efa320f2f1b59a6"'

**Comment by singpolyma** [comment]
Ok, so the problem is that BB10 is sending up an edit with a new UID and URL, but with an etag, which of course fails.  Blergh.

**Comment by singpolyma** [comment]
I worked with this a lot more, trying to get BB10 to even fetch contacts down at all, and I'm not sure what's going on.  It may just be completely broken.  I got Contacts Sync from blackberry world and that is working for now.

**Comment by allwi** [comment]
Hi, I only tried this weekend to move my calendar and address book off the public cloud.

As mentioned in this thread, the calendar sync works very well between BB10 and radicale but not the addressbook: I also can add entries but not retrieve them.
I'm using Radicale 1.1 and BB OS 10.3.2.2848.

Do you have a native solution? May how to patch Radicale so that you don't need another app on the BB device?

**Comment by nerdcraft** [comment]
Hi allwi,
can you please tell me the entries you have made in the BB OS10 caldav account? I desperately try to get my BB passport to work with radicale for month now. Nothing works!

Thank you!

Eric

**Comment by pbiering** [comment]
assuming client is no longer in use in 2024
