### ISSUE TITLE
Wrong props tag with sogo connector

### ISSUE THREAD

**Issue by julpec** [Kozea/Radicale#535]
Hello

With sogo connector (package `xul-ext-sogo-connector` on Debian or manual install version 31.0.3) the addressbook creation is failling. The "props" file is created but with this inside : 

`{"tag": "VCALENDAR"}`

After that, it's impossible to add new contacts, the addressbook file is never created.

On the server, if I modify the tag entry to `VADDRESSBOOK` it's working and synchronizing without any problem.

**Comment by liZe** [comment]
Hi,

Radicale doesn't automatically create collections anymore. This bug is fixed in the current master branch (2.0.0-pre) because Radicale now needs a MKCALENDAR or MKCOL request to create a collection, and doesn't have to guess the type of collection anymore.

If you're interested in testing 2.x, please reade the [migration guide](http://kozea.github.io/Radicale/1to2/) first!
