### ISSUE TITLE
[security] radicale 1.1.2 creates world-writeable files in filesystem_folder

### ISSUE THREAD

**Issue by zi0r** [Kozea/Radicale#589]
By default, it appears as if radicale creates world-writeable files in filesystem_folder:

> % sudo ls -lash /var/db/radicale
> total 16
> drwxr-x---   2 radicale  radicale  -  512B May  9 15:15 ./
> drwxr-xr-x  15 root      wheel     -  512B May  9 15:44 ../
> -rw-rw-rw-   1 radicale  radicale  -  2.0k May  9 15:53 user
> -rw-rw-rw-   1 radicale  radicale  -  1.0k May  9 15:52 user.props

This should be considered a security issue and resolved by specifying an appropriate mask when opening the file for write access.  A umask of 026 would be appropriate.

**Comment by Unrud** [comment]
It's documented now, with examples for systemd and daemonetization.

**Comment by zi0r** [comment]
Where is it documented?  (I looked, but had trouble finding it)

Is there a reason we don't have a sane default?  (I can't think of a good reason why it should default to world-writeable)

**Comment by Unrud** [comment]
http://radicale.org/setup/

It's in the system-wide systemd and daemonization section at the end.

**Comment by zi0r** [comment]
The proposed solutions involve something other than radicale setting the umask.  (systemd service script, external rc script, etc.).

I believe it would be more appropriate to leverage os.umask() to set this from within radicale to ensure we do not have to rely on external scripts to set this.

Examples can be found [here](http://www.programcreek.com/python/example/278/os.umask) and official documentation can be found [here](https://docs.python.org/2/library/os.html#os.umask)

**Comment by feld** [comment]
Has there been a request for a CVE assignment yet? If not I can assist in requesting one on the OSS Security mailing list.

**Comment by Unrud** [comment]
> Is there a reason we don't have a sane default?

There is no configuration for this, so we can't have any default. The **umask** is never touched.

> The proposed solutions involve something other than radicale setting the umask

The reason for not including it, is to keep it simple. You also can't setup the user or group directly in Radicale. You have to use an init system or script anyway, unless you want that it runs as root.

**Comment by feld** [comment]
> The reason for not including it, is to keep it simple.

Can you elaborate on how improving the permissions to umask 026 would break any functionality or make the software no longer "simple"? The user/group running radicale here is irrelevant. Making the users (admins) or OS packaging team solve this security issue is an odd stance. I cannot think of any reason why a user outside the owner or group should have read access to this data or what it could break to restrict it.

**Comment by Unrud** [comment]
> Making the users (admins) or OS packaging team solve this security issue is an odd stance.

If you install Radicale as a daemon, you have to create the collection folder (and possible a folder for log files). You have to set the correct permissions on these folders, to make them writable by the process and possibly deny access by others. The packager or admin has to do all of this manually. Setting the **umask** maybe protects against a configuration error.

> I cannot think of any reason why a user outside the owner or group should have read access to this data or what it could break to restrict it.

The whole idea of the file system storage is, that it can be read directly by the user or other software.

> make the software no longer "simple"?

Because it requires another configuration option and the user might not expect, that the software changes the **umask** on its own.

I reopen this issue, because I'm not sure on the best solution. We currently set the permissions of the lock file to 600, maybe we can change this to set the permissions of the collections folder to 750. But it doesn't protect log files.
