### ISSUE TITLE
Version 2.0 not working under Windows.

### ISSUE THREAD

**Issue by AB933** [Kozea/Radicale#625]
Hi,

I am trying to use version 2.0 in Windows 8.1 but can’t seem to get it to work.  I followed the 5 minute tutorial and Radicale runs and when I add localhost in a web browser I get “Radicale works!”  I can create a calendar in Lightning but it is greyed out and I can’t add events to it.  I have tried both 32 and 64 bit versions of Python 3.6.  I have tried downloading and installing Radicale manually.  I have made sure the data folder has write permission and I still can’t get it to work.  Sometimes I can get Radicale to create the user folder with EM Client but it never creates and ics file.  I tried changing things in the config file also with no luck.  I was able to get version 1.1.3 working properly with version 2.7 of Python and sync calendar entries between Lightning and EM Client.  Does anyone have an idea of what I may be doing wrong with version 2.0?

Thank you for any help!

**Comment by Unrud** [comment]
Collections are not implicitly created like in Radicale 1.x.x. You either have to use a client that lets you create them (e.g. DAVdroid) or create them manually (see http://radicale.org/clients). A third option would be to install the development version because it has a web interface that lets you create calendars and address books.

**Comment by AB933** [comment]
Thank you for your assistance.
