### ISSUE TITLE
Expand Recurring Events

### ISSUE THREAD

**Issue by balrok** [Kozea/Radicale#662]
Hello, I want to write a very simple client, for which I need the expanded date of a recurring event as in https://tools.ietf.org/html/rfc4791#section-7.8.3

This was also once asked in 
https://stackoverflow.com/questions/37711699/expanding-recurring-events-in-caldav

When retrieving the events of next week and having the recurring date expanded already by the server, it would simplify a lot.

Best Regards
Carl

**Comment by bgervan** [comment]
Hi, is this feature planned in the near future? Can we help in anything?

**Comment by Forger125** [comment]
Happy to help provide any additional info, I am running into this problem from the HomeAssistant CalDAV integration when using my home Radicale server, only displaying the first event in a series.

**Comment by pbiering** [comment]
- Is there any reference implementation as source code available for supporting this feature for "standard" reoccurring schedules + also related single shifted/canceled/adjusted ones?

- Also one has to consider a limit (and a related error message) to avoid unexpected denial-of-server attack. Think about a daily event but requested time range is e.g. 2 years -> resulting in 730 returned entries...this can even overflood a client implementation...haven't read through the RFC, but there should be 2 limits somehow:
  - max entries
  - max size (think about a schedule which has additional information stored inside, because this will be replicated in the mentioned example 730 times)

**Comment by tvogel** [comment]
This is the expand code from Sabre that is used by NextCloud:

https://github.com/sabre-io/vobject/blob/49dbd1bacba784025cc012fd7d908dd87a725914/lib/Component/VCalendar.php#L280

I donot see any arbitrary "safety" limits in that. Neither in the code leading up to that method, starting here:

https://github.com/sabre-io/dav/blob/264f567943ad904d26709fa31bcc3dcc263f3a89/lib/CalDAV/ICSExportPlugin.php#L83

Also, I would be quite hesitant because it violates data consistency. If you request daily events for two years, then it is correct to report 730 items with full detail, so any precautions should be optional and used with quite some care as the client needs to be made aware how to still request all data (by shortening the start/end interval and iterating.

**Comment by pbiering** [comment]
> Hi, is this feature planned in the near future? Can we help in anything?

based on reference code from above, one has to implement that extension into radicale, I cannot do that at the moment, did on first shot not even found where to insert...but I can test a Pull Request.

**Comment by pbiering** [comment]
Support is now implemented by https://github.com/Kozea/Radicale/pull/1292, please try master branch and file comment on PR if still a problem
