### ISSUE TITLE
New calendar event produces "Too many open files Err 24" or succeeds with delay

### ISSUE THREAD

**Issue by ThomasLemm** [Kozea/Radicale#681]
Hi,

A bug with managing files?

On: Fedora 26 with Radicale 2.1.4 with Thunderbird as a client.

When adding a new calendar event, this produces a "too many open Files [Err 24]" in the logfile. 

When I "enhancing" the radicale/__main__.py file (somewhere at the top) with 
```
import resource
resource.setrlimit(resource.RLIMIT_NOFILE, (65536, 65536))
```
inserting a calendar event succeeds. However this takes 1min and more. Also, then I have to run the radicale service as root.

I have a calendar with some 588 events.  (is this too many?). 

Kind regards

Thomas Lemm

**Comment by Unrud** [comment]
> On: Fedora 26 with Radicale 2.1.4 with Thunderbird as a client.
> When adding a new calendar event, this produces a "too many open Files [Err 24]" in the logfile.

Sounds like you have selected ``iCalendar (ICS)`` instead of ``CalDAV`` when you added the calendar in Thunderbird.

> However this takes 1min and more.

``iCalendar (ICS)`` just overwrites the whole calendar on the server, instead of synchronizing it. This should not be used during normal operation.

> A bug with managing files?

Yes, it only happens when a whole collection is uploaded. Fixed in 1821b872d2d144257fe94d7b8a449236dc3ef5bd, now at most one file per request is opened at a time

> I have a calendar with some 588 events. (is this too many?).

No.
