### ISSUE TITLE
Contact Birthdays calendar?

### ISSUE THREAD

**Issue by sprnza** [Kozea/Radicale#688]
Is it me not able to find, or there is no an option to have contacts birthdays to be aggregated in a separate or already existed calendar?

**Comment by Unrud** [comment]
This is not supported on the server-side by Radicale. Some clients support it. (e.g. [Evolution](https://wiki.gnome.org/Apps/Evolution) or  [Birthday Adapter](https://f-droid.org/packages/org.birthdayadapter/))

**Comment by dirdi** [comment]
I understand that Radicale does not support this, yet. However, it would be convenient to have such a feature on the server-side, since many clients do only support the creation of birthday events through a plugin, resulting in one to install a ton of plugins on different clients.

Maybe this bug report could be reopened, as a feature request?

Btw. sabredav for example supports this since late 2015.

**Comment by kerbless** [comment]
Quoting @dirdi, is it hard to implement?

**Comment by reitzig** [comment]
FWIW, [Birthday Adapter](https://f-droid.org/packages/org.birthdayadapter/) doesn't seem to work on Android 14 (no updates since 2016) and Google Calendar does not show birthdays from contacts other than from Google accounts (doesn't work with DAVx5 contact accounts, anyway).

@Unrud, would you be open to discussing this as a feature request? And/or reviewing a PR?

**Comment by jlbribeiro** [comment]
@reitzig Regarding Android calendar apps, [Fossify Calendar](https://github.com/FossifyOrg/Calendar) has "Add contact birthdays" and "Add contact anniversaries" options; this only "displays them" in the app, it does not generate calendars available to other Android apps.

(Personally I coded something to auto-generate a birthday and anniversaries calendar based on my address book contacts, by leveraging the [`storage.hook`](https://radicale.org/v3.html#hook) mechanism, inspired by [this comment](https://github.com/Kozea/Radicale/issues/327#issue-113212486); don't think it's worth sharing since it makes some assumptions on deployment/environment + it's coded in Go (and not Python), but I might consider it.)

Would rather have this as part of Radicale itself.
