### ISSUE TITLE
Feature request: standalone migration script

### ISSUE THREAD

**Issue by tmst** [Kozea/Radicale#719]
As I prepare to migrate my data to the 2.x branch, it seems like it would be handy to have a script to do the migration. The script would take an input file (ICS, VCARD, etc) and the path of the output directory. This would save having to figure out how to configure Radicale for 1.x just to do the migration if, as in my case, I'm not already running it (coming from 0.7.1).

**Comment by Unrud** [comment]
> it seems like it would be handy to have a script to do the migration

The export function was integrated into Radicale, because it has to support all storage plugins.

> This would save having to figure out how to configure Radicale for 1.x just to do the migration

You only have to set-up the storage backend. I don't know if the storage plugin (that you use) from version 0.7.1 is compatible with 1.1.6.

> The script would take an input file (ICS, VCARD, etc) and the path of the output directory.

If you have a single file containing the whole calendar or address book, you can upload it to Radicale directly.

Example with **curl**:

```
$ curl -u 'user:password' -X PUT 'http://localhost:5232/user/calendar/' --data-binary @calendar.ics
```
