### ISSUE TITLE
Add an Apache example to proxy documentation

### ISSUE THREAD

**Issue by earlchew** [Kozea/Radicale#760]
As an Apache user, I want some examples in the proxy documentation Apache so that I can get started more quickly.

**Comment by oakbrad** [comment]
How would you do this for a subdomain in Apache? I have been trying to set this up but just get a 404. 

ie. redirect dav.mydomain.com to work with radicale on port 5232?

**Comment by earlchew** [comment]
@oakbrad, using the guidelines at https://www.digitalocean.com/community/tutorials/how-to-use-apache-http-server-as-reverse-proxy-using-mod_proxy-extension as a starting point, I'd begin with:

```
<VirtualHost *:80>
    ProxyPass        / http://localhost:5232/ retry=0
    ProxyPassReverse / http://localhost:5232/
</VirtualHost>
```

I have not tried this, so I am pretty sure that this fragment is necessary, but not sufficient,

I also suspect that `ProxyPreserveHost On` is not required. I think radicale requires `HTTP_HOST` and `HTTP_DESTINATION` (see https://tools.ietf.org/html/rfc4229) to be set consistently so that it can tell if MOVE is trying to relocate the calendar event to a remote host.

**Comment by WheelchairArtist** [comment]
Could adding an example configuration for running Radicale as fcgi under Apache be helpful too?

Something like: 
-place radicale.fcgi under /usr/local/apache

-add FastCgiServer to Apache and let Apache handle authorization
`FastCgiServer /usr/local/apache/radicale.fcgi -processes 1 -pass-header Authorization`

-set storage locking in radicale.conf because FastCgiServer scales up when needed
`filesystem_locking = True`

-If needed add config path to server (not tested as i dont use it): 
`initial-env RADICALE_CONFIG=/../..` or `FcgidInitialEnv RADICALE_CONFIG "=/../.."` 

-add alias to fgci server
`Alias /radicale /usr/local/apache/cgi-bin/radicale.fcgi/`

-edit location as wanted
`<Location "/radicale">
</Location>`


An example Radicale config would be nice too but i'm not sure about that part which settings really get ignored and which not. I got it running this way and use htpasswd for example, this works with -pass-header Authorization which might not be needed when using remote_user or http_x_remote_user?
