### ISSUE TITLE
Apache WSGI BasicAuth wont work

### ISSUE THREAD

**Issue by klangborste** [Kozea/Radicale#909]
Hello, 

was installing Radicale 0.9 on Debian Jessie.
Decided to use also a reverse proxy and use the wsgi. I want 5 users maximum on the server, so i thought apache basic auth should be enough. If i call my URL in the browser i just get a blank site without any authentication windows pop up. The firefox developer tools say "403 Forbidden", the log files have no error and i don't really no how to fix this after searching hours in the web (also read many issues here).

**vhost.conf**
```
<VirtualHost *:443>

        ServerName domain.tld

        DocumentRoot /usr/share/radicale/
        ServerAdmin admin@sys
        WSGIDaemonProcess radicale user=www-data group=www-data threads=1
        WSGIScriptAlias / /usr/share/radicale/radicale.wsgi

        <Directory /var/lib/radicale/>
                WSGIProcessGroup radicale
                WSGIApplicationGroup %{GLOBAL}
                AllowOverride None
                Order allow,deny
                allow from all
                AuthType Basic
                AuthName "Radicale Anmeldung"
                AuthBasicProvider file
                AuthUserFile /usr/share/radicale/auth
                Require valid-user
                SSLRequireSSL
        </Directory>

        SSLEngine On
        SSLProtocol all -SSLv2 -SSLv3
        SSLHonorCipherOrder On
        SSLCompression Off
        SSLCipherSuite "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !RC4"
        SSLCertificateFile /etc/letsencrypt/live/domain.tld/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/domain.tld/privkey.pem

        LogLevel debug
        ErrorLog ${APACHE_LOG_DIR}/radicale_error.log
        CustomLog ${APACHE_LOG_DIR}/radicale_access.log combined

</VirtualHost>
```

**radicale-config (only uncommented lines)**
```
[auth]
type = None

[rights]
type = owner_write

[storage]
type = filesystem

filesystem_folder = /var/lib/radicale/collections

[logging]
config = /etc/radicale/logging
```

**/etc/radicale/logging (only uncommented lines)**
```
[loggers]
keys = root

[handlers]
keys = console,file

[formatters]
keys = simple,full

[logger_root]
level = DEBUG
handlers = file

[handler_console]
class = StreamHandler
level = DEBUG
args = (sys.stdout,)
formatter = simple

[handler_file]
class = FileHandler
args = ('/var/log/radicale/radicale.log',)
level = INFO
formatter = full

[formatter_simple]
format = %(message)s

[formatter_full]
format = %(asctime)s - %(levelname)s: %(message)s
```

**/var/log/radicale/radicale.log - all thats logged while try to acces main URL:**
```
2018-12-04 21:29:35,947 - INFO: GET request at / received
2018-12-04 21:29:36,075 - INFO: GET request at /favicon.ico received
```

**/var/log/apache2/radicale_error.log - all thats logged while try to acces main URL:**
```
[Tue Dec 04 21:28:43.736037 2018] [ssl:debug] [pid 6903] ssl_engine_kernel.c(243): [client 95.90.97.178:55410] AH02034: Initial (No.1) HTTPS request received for child 4 (server radicale.zapto.org:443)
[Tue Dec 04 21:28:43.737558 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of Require all granted: granted
[Tue Dec 04 21:28:43.737743 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of <RequireAny>: granted
[Tue Dec 04 21:28:43.738884 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of Require all granted: granted
[Tue Dec 04 21:28:43.739059 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of <RequireAny>: granted
[Tue Dec 04 21:28:43.881678 2018] [ssl:debug] [pid 6903] ssl_engine_kernel.c(243): [client 95.90.97.178:55410] AH02034: Subsequent (No.2) HTTPS request received for child 4 (server radicale.zapto.org:443)
[Tue Dec 04 21:28:43.882806 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of Require all granted: granted
[Tue Dec 04 21:28:43.882951 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of <RequireAny>: granted
[Tue Dec 04 21:28:43.883761 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of Require all granted: granted
[Tue Dec 04 21:28:43.883885 2018] [authz_core:debug] [pid 6903] mod_authz_core.c(809): [client 95.90.97.178:55410] AH01626: authorization result of <RequireAny>: granted
[Tue Dec 04 21:28:48.905909 2018] [ssl:debug] [pid 6903] ssl_engine_io.c(1004): [client 95.90.97.178:55410] AH02001: Connection closed to child 4 with standard shutdown (server radicale.zapto.org:443)
```
I would very appreciate any kind of help on this problem!  Thanks in advance.

**Comment by klangborste** [comment]
**/usr/share/radicale/radicale.wsgi**
```
#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# This file is part of Radicale Server - Calendar Server
# Copyright © 2011-2013 Guillaume Ayoub
#
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Radicale.  If not, see <http://www.gnu.org/licenses/>.

"""
Radicale WSGI file (mod_wsgi and uWSGI compliant).

"""

import radicale

radicale.log.start()
application = radicale.Application()
```

**Comment by return42** [comment]
Your ScriptAlias points to `` /usr/share/radicale/radicale.wsg`` while the Directory entry points to ``/var/lib/radicale/`` .. is this correct?

    ...
    WSGIScriptAlias / /usr/share/radicale/radicale.wsgi

            <Directory /var/lib/radicale/>
    ...

**Comment by klangborste** [comment]
Thank you, i very appreciate your help. Thats exactly what it fixed! I tried a lot things with different configurations and also changed that, but doesn't configure that directory path back to what the debian documentation says: [Debian Wiki for Radicale](https://wiki.debian.org/Radicale)
Also i think i misunderstood the directory path configuration in Apache for this application. I thought i must set the directory path to that where my collections are stored. (/var/lib/radicale/collections) But apache handles the wsgi script and basic auth to that, then the wsgi script will handle the authentication to the collections. Is that right?

**Comment by return42** [comment]
@klangborste thanks for your feedback. Apache configuration offers so many possibilities we can't discuss here ;) .. but I will try to find some words, with the hope it helps you a bit: [Directory enclose a group of directives that apply only to the named file-system directory, sub-directories, and their contents.](https://httpd.apache.org/docs/current/en/mod/core.html#directory). Mostly you will use it in combination with an [Alias Directive](https://httpd.apache.org/docs/current/en/mod/mod_alias.html#alias) which maps an URL to a file-path where your content is located (e.g. simple HTML files).

It is the same with [WSGIScriptAlias](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIScriptAlias.html), the difference is only, that the **content** is a script at that file-path-location and not a HTML page or similar.  In your example:

    WSGIScriptAlias / /usr/share/radicale/radicale.wsgi

the URL is ``/`` and the content (which is an wsgi script) is placed on the given file path ``/usr/share/radicale/radicale.wsgi``. With the Directory directive you control the access rights to the **content**. In your example it is:

                AllowOverride None
                Order allow,deny
                allow from all
                AuthType Basic
                ...
                Require valid-user

Lets summary what we are doing here, we map the URL ``/`` to a file path and we control the access in context of the file path .. that might be what confused you .. and yes,  since all URLs below ``/`` will be mapped to and handled by the WSGI process it might be much more clear if we are controlling the access rights directly in context of the URL.

In Apache you have the alternative to  control the access in context of URL. The directive for this is called [Location](https://httpd.apache.org/docs/current/en/mod/core.html#location). In your example the URL is ``/`` and the Location directive will look like this:

     <Location / >
                AllowOverride None
                Order allow,deny
                allow from all
                AuthType Basic
                ...
                Require valid-user
     </Location>

I hope this helps you to build up a more straight forward configuration then the one from Debian you referred.

The ``AuthName "Radicale Anmeldung"`` lets me suspect, that your are a native german speaker. May you find more information in my [handsOn: Apache section](https://return42.github.io/handsOn/apache_setup/index.html), there is also a chapter for [Radicale](https://return42.github.io/handsOn/radicale/radicale_server.html).  If you have annotations to the handsOn; it is a github project https://github.com/return42/handsOn

**Comment by klangborste** [comment]
Thanks for your detailed explanation. That make things much clearer. So finally i can use the directive Location for URL and Directory for file path based access control. I also used in between the Location directive, but finally i find out that i thought most of the time falsely that radicale didn't work that well. It was just that firefox was caching my BasicAuth credentials and i thought my server ain't right configured.
But thanks a lot for your clearification, helps to clear the fog :+1: 
I checked out your github project, nice documentation and on my hours of reasearch in the web i was stumbeling over exactly your webpage [Radicale](https://return42.github.io/handsOn/radicale/radicale_server.html) :-) It helped me also to understand a lot more on my way.
Thanks again
