### ISSUE TITLE
Radicale and HTTPS connections [Solved]

### ISSUE THREAD

**Issue by Chon78** [Kozea/Radicale#928]
Hello,
I'me trying to run Radicale on a Qnap NAS (TS-269L) but for security, it accepts only HTTPS connections.
So i can't open the Radicale URL page on click after installation.
Is there anything to change in the config file(s) to get it running in HTTPS ?

Many thanks for responses.

**Comment by return42** [comment]
Did you read the wiki? https://github.com/Kozea/Radicale/wiki/Simple-installation#edit-files-to-allow-ssltls-connections-from-other-machines

**Comment by Chon78** [comment]
Thanks for quick response.

I'm going to look on that and come back for a feedback.

**Comment by Chon78** [comment]
Hello,

I tried to apply the modifications in the config file but it's still not working. Noob i am...
Here is my config file after changes in the [server] part : 
```
[server]

# CalDAV server hostnames separated by a comma
# IPv4 syntax: address:port
# IPv6 syntax: [address]:port
# For example: 0.0.0.0:9999, [::]:9999
hosts = 0.0.0.0:5232

# Daemon flag
#daemon = False

# File storing the PID in daemon mode
#pid =

# Max parallel connections
#max_connections = 20

# Max size of request body (bytes)
#max_content_length = 10000000

# Socket timeout (seconds)
#timeout = 10

# SSL flag, enable HTTPS protocol
ssl = True

# SSL certificate path
certificate = /etc/ssl/radicale.cert.pem

# SSL private key
key = /etc/ssl/radicale.key.pem

# CA certificate for validating clients. This can be used to secure
# TCP traffic between Radicale and a reverse proxy
#certificate_authority =

# SSL Protocol used. See python's ssl module for available values
#protocol = PROTOCOL_TLSv1_2

# Available ciphers. See python's ssl module for available ciphers
#ciphers =

# Reverse DNS to resolve client address in logs
#dns_lookup = True

# Message displayed in the client when a password is needed
#realm = Radicale - Password Required
```
Then, i created the cert and key files with this command (completing the "common name" as it is important if i understood well) : 

`openssl req -nodes -newkey rsa:2048 -keyout /etc/ssl/radicale.key.pem -out /etc/ssl/radicale.cert.pem -x509 -days 365`

then stop ans restart Radicale but my browser (FF) still stops the connection because of non-valid certificat and no possibility to work arround.

Did i miss something ?

**Comment by return42** [comment]
Did you accept the cert in FFox?  See wiki link  ...

> By using a self-signed certificate, your browser should warn you of this fact.
> Confirm exception as you wish, but this exception is necessary to visit page.

If this was not the problem, try to set  `protocol =` to  `PROTOCOL_TLSv1_2` or `PROTOCOL_TLS` in your config .. what does the LOG say?

**Comment by Chon78** [comment]
As i understand and translate the FF error message, the site uses HSTS to tell FF to not connect the site. And so, i can't confirm any exception, the connection is simply impossible. Something to change in the FF config ?

I un-commented de protocol line in the config file with PROTOCOL_TLS or PROTOCOL_TLSv1_2 or PROTOCOL_TLSv3 with no success.

Where can i find the log file ?

When i restart Radicale i've a message telling me that the pip version (V18.0) is out to date (V19.0.2).
Something to have with my problem ?

**Comment by return42** [comment]
> EDIT : Something with FF confirmed because i tried through Edge and i could confirm the exception.

Search the web for: _How to Delete HSTS Settings in Firefox_

**Comment by Chon78** [comment]
That was it ! Thanks Return42 !

Question of security : isn't that dangerous to accept exception on that URL ? I mean, do i open a great door on my NAS if i leave this exception ?

Last question : At the next upgrade of Radicale, will i have to modifie the config file again ?

**Comment by return42** [comment]
> Question of security : isn't that dangerous to accept exception on that URL ? I mean, do i open a great door on my NAS if i leave this exception ?

Simple explanation (not technical correct) ..

When your FF connects to your Radicale server, the server response a [HSTS](https://de.wikipedia.org/wiki/HTTP_Strict_Transport_Security) _flag_. If a WEB-browser sees this _flag_, the browser is instructed to be very strict with the security protocol. You have done your first tests (connects) over HTTP and after you switched the server to HTTPS. This is not a normal use-case. This was detected (cached) by FF and is a volataion of (strict) security. Therefore a browser has to block (because it smells like an attack).  So FF is working fine and does not allow you to except the cert from this server (to security reasons).

Excepting self signed certificates is done on the client side (you accept in your FF or your DAV client) and is needed, because there cant be a third party [CA](https://en.wikipedia.org/wiki/Certificate_authority) validating your self-signed certs.  If you want a cert which does not need to be accepted by he client, you need a cert which is issued by a CA e.g. [Let's Encrypt](https://letsencrypt.org/).

> I mean, do i open a great door on my NAS if i leave this exception ?

no, all explanation above is talking about security on the client side.

Anyway, if this is all new to you I can't recommend to place your server in the internet .. but I guess you just use it from you intranet (which is unproblematic).

> Last question : At the next upgrade of Radicale, will i have to modifie the config file again ?

normally: no

**Comment by return42** [comment]
> That was it ! Thanks Return42 !

feel welcome .. can you please close this issue / thanks!

**Comment by Chon78** [comment]
Many thanks for this explanation.

I close this issue.
