### ISSUE TITLE
How to implement SSL

### ISSUE THREAD

**Issue by jmfoleyjr** [Kozea/Radicale#945]
I am trying to use SSL with Radicale. I've checked the thread https://github.com/Kozea/Radicale/issues/879, but that hasn't solved my problem. I get the error, "[7f627c4f0700] ERROR: An exception occurred during request: SSL handshake failed: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)". I'm using a known working certificate which works with https and sendmail/TLS on the same server. My current config is:

[server]
hosts = 0.0.0.0:5232
ssl = True
certificate = /etc/mail/certs/cert.pem
key = /etc/mail/certs/privkey.pem
protocol = PROTOCOL_TLSv1_2
certificate_authority = /etc/mail/certs/root.cer

Any ideas?

**Comment by donjan** [comment]
Do you have it set up as with a radicale user and can it read the cert files? (sudo -u radicale nano cert.pem)

**Comment by jmfoleyjr** [comment]
donjan, thanks for your reply. I was able to get it working, sort of. The trick was to specify the URL as https, not http. That let me access the calendar. The "SSL: WRONG_VERSION_NUMBER" was completely misleading, and threw me down the wrong path. I removed the protocol and certificate_authority settings as they were not needed. But now another related problem ...

I am running radicale as a non-root user: su radicale --command "/usr/bin/radicale -d", however, unless I make the cert key readable, I get the error, "Failed to read SSL key '/etc/ssl/certs/OHPRS/GoDaddy/mail.ohprs.org.key': [Errno 13] Permission denied: '/etc/ssl/certs/OHPRS/GoDaddy/mail.ohprs.org.key'". But, if I make it readable then sendmail will refuse TLS connections with the error, "file /etc/ssl/certs/OHPRS/GoDaddy/mail.ohprs.org.key unsafe: Group readable file"

What's the solution? Can I only run radicale as root?

**Comment by donjan** [comment]
The command in my previous comment shows this issue, and sendmail is correct to refuse the the g+r solution, because certs should be at 400.

If you use ACL, you can add the radicale user to the allowed readers. Another solution (which I tend to use) is separate certificates, one belonging fully to the radicale user.
A poor yet possibly working solution would be to give the cert to the radicale user and relying on sendmail to be able to read it as root, but don't do this.

**Comment by jmfoleyjr** [comment]
I tried a self-signed certificate, but radicale gives the error, "ssl.SSLError: [SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2484)." So, apparently I need a *real* certification from an actual Certificate Authority. At this point, I'm experimenting, so I don't want to buy a certificate.

The ACL is a good suggestion and I may experiment with that later. The main problem with that is it's all a bit hidden and would need some careful documentation if someone other than myself were to renew certificates in the future. Instead, I've basically done your not-recommend 3rd solution. I've copied the key file the the radicale home directory and given it ower-only rw permission. I will put a README file in that home directory explaining what I've done. So far, this seems to work.

**Comment by Tntdruid** [comment]
Get a real cert free from https://letsencrypt.org/

**Comment by donjan** [comment]
Congratulations, now an exploit in Radicale will allow folks to jack your email signing ;)

You've tried to use CA signing on a self-signed cert?
You can do that if you distribute the cert resulting from the signkey command to your clients, but for testing purposes a simple
`openssl genrsa 2048 > test.key` and `openssl req -new -x509 -nodes -sha256 -key test.key -out test.cert` will work fine, of course with the usual "are you sure about this certificate?" warnings in Thunderbird, OpenSync, etc.

As usual, like Tntdruid already mentioned, the best choice is letsencrypt.
Especially since you're now effectively using two different files, which is more "hidden" and messy system administration when the time comes to update, revoke or extend them, despite any best efforts of adding README files.

**Comment by jmfoleyjr** [comment]
An exploit in Radicale? Say it isn't so!!! I will explore using letsencrypt. That's going to be a whole 'nuther line of testing with certbot, etc. For short-term testing purposes, I'll use my two-files solution. Just don't tell anybody! I've got more questions I'll post as a separate thread since they're not related to SSL.
Thanks all for the very helpful feedback.

**Comment by Tntdruid** [comment]
https://github.com/Neilpang/acme.sh if you want to use dns mode, aka no need to open 80 and 443 i firewall.
