### ISSUE TITLE
External calendar sync

### ISSUE THREAD

**Issue by Yamakaky** [Kozea/Radicale#98]
Hi

Sorry for the title, I don't know how name it. I talk about regularly pull a distant calendar into the radicale instance. My university permit us to get our schedule online, so I would like to create a read-only calendar filled and updated from an URL. Is it possible ?

Thanks for your amazing software.

**Comment by timokau** [comment]
I just had this problem. In case anybody else (or future me) wants to synchronise external calendars, I'll document my solution here:

# Create an empty calendar

This can be done through whatever client you are using, or with a simple curl command (see https://radicale.org/clients/). That will also take care of splitting up one single ics file into one file per event (as radicale stores calendars).

```
$ curl -u '<radicale-user>/<radicale-pass>' -X MKCOL 'http://localhost:5232/<radicale-user>/<calendar-name>' --data \
'<?xml version="1.0" encoding="UTF-8" ?>
<create xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:I="http://apple.com/ns/ical/">
  <set>
    <prop>
      <resourcetype>
        <collection />
        <C:calendar />
      </resourcetype>
      <C:supported-calendar-component-set>
        <C:comp name="VEVENT" />
        <C:comp name="VJOURNAL" />
        <C:comp name="VTODO" />
      </C:supported-calendar-component-set>
      <displayname>Calendar</displayname>
      <C:calendar-description>Example calendar</C:calendar-description>
      <I:calendar-color>#ff0000ff</I:calendar-color>
    </prop>
  </set>
</create>'
```

Substitute `localhost:5232` if you're not running this on the radicale server configured with the default port. Also substitute `displayname` and `calendar-description`.

# Create a script to sync an external calendar

You can create radicale events with `curl` (see https://piware.de/post/2018-05-01-android-degoogle/). This will over-write old events (so the entire calendar will be re-created every time).

Create `/usr/local/bin/radicale-external-sync` with the following contents:

```
#!/bin/sh
radicale_user='timo'
radicale_pass='Correct Horse Battery Staple'¬
external_calendar_url='https://upbhack.de/events/index.ics'¬
local_calendar_name='ctf'¬
radicale_url='https://localhost'¬
radicale_port='5232' # default port¬
¬
# --insecure is only needed if you use a self-signed certificate
curl --insecure \¬
	--user "$radicale_user:$radicale_pass" \¬
	-X PUT "$radicale_url:$radicale_port/$radicale_user/$local_calendar_name/" \¬
	--data-binary "$( curl "$external_calendar_url" )"¬
```

Make sure `local_calendar_name` is the same as the previously created calendar (not the display name). I also recommend to set the permissions of the script appropriately so that other users (or malicious programs) can't read the radicale password:

```
$ sudo chown root:root /usr/local/bin/radicale-external-sync
$ sudo chmod 700 /usr/local/bin/radicale-external-sync
```

# Create a system timer

Now create a systemd service to sync the calendars and an accompanying tiemer to execute it (doesn't have to be "daily" of course):

`/etc/systemd/system/radicale-external-calendar.service`

```
[Unit]
Description=Sync external calendars with radicale

[Service]
Type=oneshot
ExecStart=/usr/local/bin/radicale-external-sync
```

`/etc/systemd/system/radicale-external-calendar.timer`

```
[Unit]
Description=Synchronize external calendars

[Timer]
OnCalendar=daily
Persistent=true

[Install]
WantedBy=timers.target
```

Now tell systemd to look for those new units:

```
$ systemctl daemon-reload
```

and test the service:

```
$ systemctl start radicale-external-calendar.service
```

You should now be able to sync the new calendar with your client. If that worked, enable the timer:

```
$ systemctl enable radicale-external-calendar.timer
```

Thats it.

**Comment by MatthewHana** [comment]
@charliesz  Remove 'd:' from the propertyupdate, set, and prop element tags in your XML.

The following should fix your issue:
```
curl -u '$USER:$PASS' -X PROPPATCH '$URL' --data '<?xml version="1.0" encoding="UTF-8" ?><propertyupdate xmlns:d="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><set><prop><displayname>NeuerName</displayname></prop></set></propertyupdate>'
```

**Comment by charliesz** [comment]
@MatthewHana 
Thank you for your fast response it worked with d:. juhu =D

My solution for name, desription, color after an update with the external calendar is now:
`curl -u 'charlie:pw -X PROPPATCH 'http://192.168.178.5:5232/charlie/IFSC/' --data '<?xml version="1.0" encoding="UTF-8" ?><d:propertyupdate xmlns:d="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:ICAL="http://apple.com/ns/ical/"><d:set><d:prop><d:displayname>IFSC</d:displayname><C:calendar-description>IFSC Events</C:calendar-description><ICAL:calendar-color>#FF0000</ICAL:calendar-color></d:prop></d:set></d:propertyupdate>'`


When using your command without d: for the displayname the following is happening:
`curl -u 'charlie:pw' -X PROPPATCH 'http://192.168.178.5:5232/charlie/IFSC/' --data '<?xml version="1.0" encoding="UTF-8" ?><propertyupdate xmlns:d="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav"><set><prop><displayname>IFSC</displayname></prop></set></propertyupdate>'`
gives the output:
`<?xml version='1.0' encoding='utf-8'?><multistatus xmlns="DAV:"><response><href>/charlie/IFSC/</href><propstat><prop /><status>HTTP/1.1 200 OK</status></propstat></response></multistatus>`
in the gui the name stays as "charlie/IFSC"
when I take a look at all properties with PROPFIND the displayname stays "charlie/IFSC"
 
`curl -u 'charlie:pw' -X PROPFIND 'http://192.168.178.5:5232/charlie/IFSC/' -H 'Depth: 0'`
the output
`<?xml version='1.0' encoding='utf-8'?>
<multistatus xmlns="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav" xmlns:CS="http://calendarserver.org/ns/">
  <response>
    <href>/charlie/IFSC/</href>
    <propstat>
      <prop>
        <principal-collection-set><href>/</href></principal-collection-set>
        <current-user-principal><href>/charlie/</href></current-user-principal>
        <current-user-privilege-set>
          <privilege><read /></privilege>
          <privilege><all /></privilege>
          <privilege><write /></privilege>
          <privilege><write-properties /></privilege>
          <privilege><write-content /></privilege>
        </current-user-privilege-set>
        <supported-report-set>
          <supported-report>
            <report><expand-property /></report>
          </supported-report>
          <supported-report>
            <report><principal-search-property-set /></report>
          </supported-report>
          <supported-report>
            <report><principal-property-search /></report>
          </supported-report>
          <supported-report>
            <report><sync-collection /></report>
          </supported-report>
          <supported-report>
            <report><C:calendar-multiget /></report>
          </supported-report>
          <supported-report>
            <report><C:calendar-query /></report>
          </supported-report>
        </supported-report-set>
        <resourcetype><C:calendar /><collection /></resourcetype>
        <owner><href>/charlie/</href></owner>
        <getetag>"XXXX"</getetag>
        <getlastmodified>Thu, 12 Oct 2023 09:02:13 GMT</getlastmodified>
        <getcontenttype>text/calendar</getcontenttype>
        <getcontentlength>25239</getcontentlength>
        <displayname>charlie/IFSC</displayname>
        <sync-token>http://radicale.org/ns/sync/XXXX</sync-token>
        <CS:getctag>"XXXX"</CS:getctag>
        <C:supported-calendar-component-set>
          <C:comp name="VTODO" />
          <C:comp name="VEVENT" />
          <C:comp name="VJOURNAL" />
        </C:supported-calendar-component-set>
      </prop>
      <status>HTTP/1.1 200 OK</status>
    </propstat>
  </response>
</multistatus>`

I will not investigate that further, because I have now a working solution but wanted to leave a full report.

**Comment by Robin-Sch** [comment]
I got external calendar to work using this:
https://github.com/Kozea/Radicale/issues/733#issuecomment-348217332

**Comment by Robin-Sch** [comment]
Is it also possible to set the type? Right now it always overwrites it with "calendar, journal and tasks", while (in my case) it only should be calendar.
